baseurl      = "localhost"
title        = "Portfolio"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[author]
name = "Sai Ramya Linga"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  description    = "Portfolio"
  keywords    = "sairamyalinga, linga, portfolio, full stack developer"
  homeSubtitle = "Software Engineer at <a href='https://internpro.ai/' target='_blank'>InternPro.ai</a> | Transforming ideas into reality <br> MS in Computer Engineering @ ASU | ex. <a href='https://www.tcs.com/' target='_blank'>TCS</a>"
  profileImage  = "https://avatars.githubusercontent.com/u/67336902?s=400&u=a5852f995e105283e319cd0a08d1d6679ca3c0fb&v=4"
  defaultTheme = "light"
  themeColor = "#252627"


 [params.logo]
    logoMark           = ">"
    logoText           = "cd /home/"  
    logoHomeLink       = "/"
    logoCursorPathname = true
    
# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = true

 # Social icons
[[params.social]]
name = "github"
url = "https://github.com/sairamyalinga"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/sairamyalinga/"

[[params.social]]
name = "email"
url = "mailto:sairamyalinga@gmail.com"

[[params.social]]
name = "telegram"
url = "https://t.me/sairamyalinga"

# And you can even create a generic menu
[menu]
[[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "about/"
  weight     =  1
[[menu.main]]
  identifier = "projects"
  name       = "Projects"
  url        = "projects/"
  weight     = 2

[[menu.main]]
  identifier = "resume"
  name       = "Resume"
  url        = "/resume"
   weight     = 3
  [[menu.main.params]]
    target     = "_blank"
[[menu.main]]
  identifier = "TIL"
  name       = "TIL"
  url        = "posts/"
   weight     = 4





